import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableRow
} from "@mui/material";

import { Report } from "../api/report.types";
import ReportStatus from "./ReportStatus";

interface Props {
  reports: Report[];
}

export default function ReportTable({
  reports,
}: Props) {
  return (
    <Table>

      <TableHead>

        <TableRow>

          <TableCell>Title</TableCell>

          <TableCell>Type</TableCell>

          <TableCell>Generated By</TableCell>

          <TableCell>Date</TableCell>

          <TableCell>Status</TableCell>

        </TableRow>

      </TableHead>

      <TableBody>

        {reports.map((report) => (

          <TableRow key={report.id}>

            <TableCell>{report.title}</TableCell>

            <TableCell>{report.type}</TableCell>

            <TableCell>{report.generatedBy}</TableCell>

            <TableCell>{report.generatedAt}</TableCell>

            <TableCell>

              <ReportStatus status="Generated" />

            </TableCell>

          </TableRow>

        ))}

      </TableBody>

    </Table>
  );
}